install react router dom
ComicScrip/lyon-react-mars22-p2g4 pull request #3
Opened 2022-04-07 09:39 UTC by fflachat

2022-04-07 10:00 UTC, jmj69 approved these changes
ok

2022-04-12 13:43 UTC, NycoChavanoud submitted a review, later dismissed

2022-04-12 21:40 UTC, ComicScrip commented
Merci de connecter l'issue correspondante pour qu'on sache quoi tester

2022-04-13 07:50 UTC, jmj69 submitted a review, later dismissed

2022-04-15 13:34 UTC, NycoChavanoud requested changes

2022-04-15 13:34 UTC, NycoChavanoud commented on src/components/Header.css
> +    background: lightgreen;
code mort

2022-04-18 18:34 UTC, ComicScrip commented on src/components/Header.css
> +    background: lightgreen;
oui

2022-04-19 14:33 UTC, ComicScrip submitted a review, later dismissed

2022-04-19 14:34 UTC, ComicScrip approved these changes

2022-04-19 14:35 UTC, merged