Contact form
ComicScrip/lyon-react-mars22-p2g4 pull request #35
Opened 2022-04-14 12:53 UTC by ChrichriR

2022-04-14 13:23 UTC, jmj69 submitted a review, later dismissed

2022-04-18 18:32 UTC, ComicScrip commented on src/components/DevMembers.js
> +export default function DevMembers({ firstName, lastName, avatarUrl }) {
Un "s" dans le nom porte à confusion, ici on traite un élément et non plusieurs

2022-04-20 15:00 UTC, Sim-guy submitted a review, later dismissed

2022-04-21 10:05 UTC, NycoChavanoud requested changes
Le code est propre, cependant les visuels ne correspondent pas vraiment à la maquette . 

C'est vraiment pas loin, mais attention au padding (de ton "lorem" entre autre..) les borders sont différents (none?) ... Un petit effort avec en bonus eventuel enlever ce vilain Lorem par un vrai petit texte sympa..

2022-04-21 12:39 UTC, merged