Meteo
ComicScrip/lyon-react-mars22-p2g4 pull request #37
Opened 2022-04-15 09:33 UTC by Isma69

2022-04-18 18:16 UTC, ComicScrip commented on src/App.js
> +import MeteoForecast7 from './components/MeteoForecast+7';
Ca fait beaucoup de composants non ? Cette approche n'est pas la bonne, merci de venir en discuter avec moi

2022-04-18 18:16 UTC, ComicScrip commented on src/components/CurrentMeteoIcon.js
> +const apiKey = 'b9a0c0a87d7845a4ed3bd3a5841bb88e';
à mettre dans un `.env` please

2022-04-18 18:16 UTC, ComicScrip commented on src/components/CurrentMeteoIcon.js
> +function GetCurrentIconMeteoData() {
Le nom d'un composant ne devrait pas commencer par un verbe

2022-04-18 18:16 UTC, ComicScrip commented on src/components/MeteoData.json
> +{
A quoi sert ce fichier ?

2022-04-19 12:16 UTC, Isma69 commented on src/components/CurrentMeteoIcon.js
> +function GetCurrentIconMeteoData() {
J'ai modifié le nom du composant de manière à ce qu'il ne commence pas par un verbe

2022-04-19 12:16 UTC, Isma69 commented on src/components/MeteoData.json
> +{
Il ne servait à rien, il a été supprimé

2022-04-20 12:21 UTC, Isma69 commented on src/App.js
> +import MeteoForecast7 from './components/MeteoForecast+7';
Oui effectivement j'ai passé ça dans des props, ça a bien allégé tout ça.

2022-04-20 14:55 UTC, Isma69 commented on src/components/CurrentMeteoIcon.js
> +const apiKey = 'b9a0c0a87d7845a4ed3bd3a5841bb88e';
C'est bien mis dans un fichier .env

2022-04-21 10:10 UTC, NycoChavanoud requested changes
A mon avis ut n'as pas push ce que tu avais fait en local??? 

ET ATTENTION ON MERGE LES PR SUR DEV ET PAS SUR MAIN

2022-04-21 10:10 UTC, NycoChavanoud commented on src/App.js
> +import MeteoForecast7 from './components/MeteoForecast+7';
Rien à été changé..

2022-04-21 12:09 UTC, closed without merging

2022-04-21 12:09 UTC, Isma69 commented
Pas nécessaire.