Display maps
ComicScrip/lyon-react-mars22-p2g4 pull request #40
Opened 2022-04-15 12:11 UTC by fflachat

2022-04-18 17:54 UTC, ComicScrip commented
Issue non spécifiée, je ne sais pas quoi tester

2022-04-18 17:58 UTC, ComicScrip commented on src/components/DisplayMap.js
> +export default function DisplayMap({ path, position }) {
"Map" plutôt que "DisplayMap" ?

2022-04-22 13:23 UTC, Sim-guy approved these changes

2022-04-24 11:06 UTC, ComicScrip requested changes

2022-04-24 11:06 UTC, ComicScrip commented on src/screens/PathDetails.js
> +      <button
Utilisez Link plutot

2022-04-24 17:17 UTC, fflachat commented on src/screens/PathDetails.js
> +      <button
Button modifié pour un Link

2022-04-25 06:40 UTC, ComicScrip submitted a review, later dismissed

2022-04-25 15:27 UTC, ComicScrip submitted a review, later dismissed

2022-05-03 14:00 UTC, ComicScrip requested changes

2022-05-03 14:00 UTC, ComicScrip commented on src/components/MeteoTemp.js
> +      <ul>{Math.round(meteoTemp)}°C</ul>
attention pas sémantique

2022-05-03 14:00 UTC, ComicScrip commented on src/components/Photos.js
> +        <div>Aucune photo n'a pu être récupéré pour votre parcours</div>
récuprerée

2022-05-03 14:00 UTC, ComicScrip commented on src/screens/LiveView.js
> +        `https://lyon-react-mars22-p2g4-api.comicscrip.duckdns.org/api/paths/${id}`
url en dur

2022-05-03 14:00 UTC, ComicScrip commented on src/screens/PathDetails.js
> +        `https://lyon-react-mars22-p2g4-api.comicscrip.duckdns.org/api/paths/${id}`
url en dur

2022-05-03 14:00 UTC, ComicScrip commented on src/screens/Paths.js
> +      .get(`${process.env.REACT_APP_PATHS_API_URL}/api/paths?name=${keyword}`)
REACT_APP_API_URL

2022-05-04 12:42 UTC, ComicScrip approved these changes

2022-05-04 12:42 UTC, merged