Liveview
ComicScrip/lyon-react-mars22-p2g4 pull request #45
Opened 2022-04-20 15:14 UTC by fflachat

2022-04-22 13:24 UTC, Sim-guy approved these changes

2022-04-24 11:18 UTC, ComicScrip requested changes

2022-04-24 11:18 UTC, ComicScrip commented on src/components/RunInformations/RunInformations.js
> +  });
manquerait pas des dépendances ici ?

2022-04-24 11:18 UTC, ComicScrip commented on src/components/RunInformations/RunInformations.js
> +    window.location.href = '/recaprace';
pourquoi faire une redirection ?

2022-04-24 17:25 UTC, fflachat commented on src/components/RunInformations/RunInformations.js
> +    window.location.href = '/recaprace';
J'ai supprimé la redirection et ajouter un Link sur le bouton Reset (renommé en Stop)

2022-04-24 17:29 UTC, fflachat commented on src/components/RunInformations/RunInformations.js
> +  });
J'ai ajouté les dépendances à isActived isPaused et time.

2022-04-25 09:25 UTC, merged